// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

type DistinguishingFeature struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Intensity   *float64 `json:"intensity"`
}

type DistinguishingFeatureInput struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Intensity   *float64 `json:"intensity"`
}

type Dog struct {
	ID                     string                   `json:"id"`
	Name                   string                   `json:"name"`
	OwnerID                string                   `json:"ownerId"`
	TailLength             *int                     `json:"tailLength"`
	DistinguishingFeatures []*DistinguishingFeature `json:"distinguishingFeatures"`
}

type DogInput struct {
	Name                   string                        `json:"name"`
	TailLength             *int                          `json:"tailLength"`
	DistinguishingFeatures []*DistinguishingFeatureInput `json:"distinguishingFeatures"`
}

type FeatureFilterInput struct {
	FeatureName string `json:"featureName"`
}

type Header struct {
	Name   string    `json:"name"`
	Values []*string `json:"values"`
}

type HumanInput struct {
	Name string      `json:"name"`
	Dogs []*DogInput `json:"dogs"`
}
