// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

type DistinguishingFeature struct {
	Description        string   `json:"description"`
	SpottingDifficulty *float64 `json:"spottingDifficulty"`
}

type DistinguishingFeatureInput struct {
	Description        string   `json:"description"`
	SpottingDifficulty *float64 `json:"spottingDifficulty"`
}

type Dog struct {
	ID                     string                   `json:"id"`
	Name                   string                   `json:"name"`
	OwnerID                string                   `json:"ownerId"`
	TailLength             *int                     `json:"tailLength"`
	DistinguishingFeatures []*DistinguishingFeature `json:"distinguishingFeatures"`
}

type DogInput struct {
	Name                   string                        `json:"name"`
	TailLength             *int                          `json:"tailLength"`
	DistinguishingFeatures []*DistinguishingFeatureInput `json:"distinguishingFeatures"`
}

type Header struct {
	Name   string    `json:"name"`
	Values []*string `json:"values"`
}

type Human struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Dogs []*Dog `json:"dogs"`
}

type HumanInput struct {
	Name string      `json:"name"`
	Dogs []*DogInput `json:"dogs"`
}
